services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ROBOFLOW_API_URL=${ROBOFLOW_API_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 